# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Gymnastic' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gymnastic
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'ObjectMapper', '~> 3.3'
  pod 'Alamofire', '~> 4.7'
  pod 'SVProgressHUD'
  pod 'RealmSwift'
end
