# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Gymnastic' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gymnastic
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'ObjectMapper', '~> 3.3'
  pod 'Alamofire', '~> 4.7'
  pod 'SVProgressHUD'
  pod 'RealmSwift'
  pod 'youtube-ios-player-helper', '~> 0.1.1'
  pod 'Charts', '~> 3.0.1'
  pod 'RealmSwift', '~> 3.7.6'
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.0'
          end
      end
  end
end
